// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Utils$ReactTemplate from "./Utils.bs.js";
import * as Config$ReactTemplate from "./Config.bs.js";
import * as Router$ReactTemplate from "./Router.bs.js";
import * as ReactTransitionGroup$ReactTemplate from "./ReactTransitionGroup.bs.js";

((require('../../../src/App.scss')));

var component = ReasonReact.reducerComponent("App");

function make(currentRoute, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function (self) {
              var init = self[/* state */1];
              var init$1 = self[/* state */1][/* nav */1];
              return /* record */[
                      /* user */init[/* user */0],
                      /* nav : record */[
                        /* isOpen */false,
                        /* isSwiping */init$1[/* isSwiping */1],
                        /* position */init$1[/* position */2],
                        /* width */init$1[/* width */3]
                      ]
                    ];
            }),
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = List.hd(List.rev(self[/* state */1][/* nav */1][/* position */2]));
              var x = match[0];
              var match$1 = List.hd(self[/* state */1][/* nav */1][/* position */2]);
              var x$prime = match$1[0];
              var match$2 = self[/* state */1][/* nav */1][/* isOpen */0];
              var match$3 = self[/* state */1][/* nav */1][/* isOpen */0];
              var match$4 = self[/* state */1][/* nav */1][/* isSwiping */1][0];
              var tmp;
              if (match$4) {
                var match$5 = x$prime - x > 0.0;
                tmp = {
                  transition: "none",
                  transform: "translateX(" + (Pervasives.string_of_float(match$5 ? 0.0 : x$prime - x) + "0px)")
                };
              } else {
                tmp = { };
              }
              return React.createElement("div", {
                          className: "App" + (
                            match$2 ? " overlay" : ""
                          ),
                          onClick: (function () {
                              return Curry._1(self[/* send */3], /* ToggleMenu */Block.__(0, [false]));
                            }),
                          onTouchEnd: (function ($$event) {
                              return Curry._1(self[/* send */3], /* TouchEnd */Block.__(3, [Utils$ReactTemplate.TouchList[/* first */0]($$event.changedTouches).clientX]));
                            }),
                          onTouchMove: (function ($$event) {
                              return Curry._1(self[/* send */3], /* TouchMove */Block.__(2, [Utils$ReactTemplate.TouchList[/* first */0]($$event.changedTouches).clientX]));
                            }),
                          onTouchStart: (function ($$event) {
                              return Curry._1(self[/* send */3], /* TouchStart */Block.__(1, [Utils$ReactTemplate.TouchList[/* first */0]($$event.changedTouches).clientX]));
                            })
                        }, React.createElement("header", undefined, React.createElement("a", {
                                  onClick: (function ($$event) {
                                      $$event.stopPropagation();
                                      return Curry._1(self[/* send */3], /* ToggleMenu */Block.__(0, [!self[/* state */1][/* nav */1][/* isOpen */0]]));
                                    })
                                }, React.createElement("svg", {
                                      viewBox: "0 0 24 24"
                                    }, React.createElement("path", {
                                          d: "M21 11h-18c-0.6 0-1 0.4-1 1s0.4 1 1 1h18c0.6 0 1-0.4 1-1s-0.4-1-1-1z"
                                        }), React.createElement("path", {
                                          d: "M3 7h18c0.6 0 1-0.4 1-1s-0.4-1-1-1h-18c-0.6 0-1 0.4-1 1s0.4 1 1 1z"
                                        }), React.createElement("path", {
                                          d: "M21 17h-18c-0.6 0-1 0.4-1 1s0.4 1 1 1h18c0.6 0 1-0.4 1-1s-0.4-1-1-1z"
                                        }))), React.createElement("h1", undefined, Config$ReactTemplate.routeToTitle(currentRoute))), React.createElement("nav", {
                              ref: Curry._1(self[/* handle */0], (function (ref, self) {
                                      self[/* state */1][/* nav */1][/* width */3][0] = (ref == null) ? 0.0 : ref.clientWidth;
                                      return /* () */0;
                                    })),
                              className: match$3 ? "active" : "",
                              style: tmp,
                              onClick: (function ($$event) {
                                  $$event.stopPropagation();
                                  return /* () */0;
                                })
                            }, React.createElement("header", undefined, React.createElement("a", {
                                      onClick: (function () {
                                          return Curry._1(self[/* send */3], /* ToggleMenu */Block.__(0, [false]));
                                        })
                                    }, React.createElement("svg", {
                                          viewBox: "0 0 32 32"
                                        }, React.createElement("path", {
                                              d: "M12.586 27.414l-10-10c-0.781-0.781-0.781-2.047 0-2.828l10-10c0.781-0.781 2.047-0.781 2.828 0s0.781 2.047 0 2.828l-6.586 6.586h19.172c1.105 0 2 0.895 2 2s-0.895 2-2 2h-19.172l6.586 6.586c0.39 0.39 0.586 0.902 0.586 1.414s-0.195 1.024-0.586 1.414c-0.781 0.781-2.047 0.781-2.828 0z"
                                            })), Config$ReactTemplate.routeToTitle(currentRoute)), React.createElement("svg", {
                                      viewBox: "0 0 32 32"
                                    }, React.createElement("path", {
                                          d: "M8 10c0-4.418 3.582-8 8-8s8 3.582 8 8c0 4.418-3.582 8-8 8s-8-3.582-8-8zM24 20h-16c-4.418 0-8 3.582-8 8v2h32v-2c0-4.418-3.582-8-8-8z"
                                        })), React.createElement("p", undefined, self[/* state */1][/* user */0][/* name */0]), React.createElement("p", undefined, self[/* state */1][/* user */0][/* email */1])), React.createElement("label", undefined, "home"), React.createElement("ul", undefined, React.createElement("li", undefined, ReasonReact.element(/* None */0, /* None */0, Router$ReactTemplate.NavLink[/* make */1](/* Home */0, /* None */0, /* None */0, /* array */["Home"])))), React.createElement("label", undefined, "pages"), React.createElement("ul", undefined, React.createElement("li", undefined, ReasonReact.element(/* None */0, /* None */0, Router$ReactTemplate.NavLink[/* make */1](/* Page1 */1, /* None */0, /* None */0, /* array */["Page1"]))), React.createElement("li", undefined, ReasonReact.element(/* None */0, /* None */0, Router$ReactTemplate.NavLink[/* make */1](/* Page2 */2, /* None */0, /* None */0, /* array */["Page2"]))), React.createElement("li", undefined, ReasonReact.element(/* None */0, /* None */0, Router$ReactTemplate.NavLink[/* make */1](/* Page3 */3, /* None */0, /* None */0, /* array */["Page3"]))))), React.createElement("main", undefined, ReasonReact.element(/* None */0, /* None */0, ReactTransitionGroup$ReactTemplate.TransitionGroup[/* make */0](/* array */[Config$ReactTemplate.routeToComponent(currentRoute)]))));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* user : record */[
                        /* name */"Person Name",
                        /* email */"person@email.com"
                      ],
                      /* nav : record */[
                        /* isOpen */false,
                        /* isSwiping */[false],
                        /* position : :: */[
                          /* tuple */[
                            0.0,
                            0.0
                          ],
                          /* [] */0
                        ],
                        /* width */[0.0]
                      ]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    var isOpen = action[0];
                    var init = state[/* nav */1];
                    return /* UpdateWithSideEffects */Block.__(2, [
                              /* record */[
                                /* user */state[/* user */0],
                                /* nav : record */[
                                  /* isOpen */isOpen,
                                  /* isSwiping */init[/* isSwiping */1],
                                  /* position */init[/* position */2],
                                  /* width */init[/* width */3]
                                ]
                              ],
                              (function () {
                                  if (isOpen) {
                                    return ( document.documentElement.style.overflow = "hidden");
                                  } else {
                                    return ( document.documentElement.style.overflow = "");
                                  }
                                })
                            ]);
                case 1 : 
                    if (state[/* nav */1][/* isOpen */0]) {
                      state[/* nav */1][/* isSwiping */1][0] = true;
                    }
                    var init$1 = state[/* nav */1];
                    return /* Update */Block.__(0, [/* record */[
                                /* user */state[/* user */0],
                                /* nav : record */[
                                  /* isOpen */init$1[/* isOpen */0],
                                  /* isSwiping */init$1[/* isSwiping */1],
                                  /* position : :: */[
                                    /* tuple */[
                                      action[0],
                                      performance.now()
                                    ],
                                    /* [] */0
                                  ],
                                  /* width */init$1[/* width */3]
                                ]
                              ]]);
                case 2 : 
                    if (state[/* nav */1][/* isSwiping */1][0]) {
                      var init$2 = state[/* nav */1];
                      return /* Update */Block.__(0, [/* record */[
                                  /* user */state[/* user */0],
                                  /* nav : record */[
                                    /* isOpen */init$2[/* isOpen */0],
                                    /* isSwiping */init$2[/* isSwiping */1],
                                    /* position : :: */[
                                      /* tuple */[
                                        action[0],
                                        performance.now()
                                      ],
                                      state[/* nav */1][/* position */2]
                                    ],
                                    /* width */init$2[/* width */3]
                                  ]
                                ]]);
                    } else {
                      return /* NoUpdate */0;
                    }
                case 3 : 
                    state[/* nav */1][/* isSwiping */1][0] = false;
                    var match = state[/* nav */1][/* position */2];
                    var velocity;
                    if (match) {
                      var match$1 = match[1];
                      if (match$1) {
                        var match$2 = match$1[0];
                        var match$3 = match[0];
                        velocity = (match$3[0] - match$2[0]) / (match$3[1] - match$2[1]);
                      } else {
                        velocity = 0.0;
                      }
                    } else {
                      velocity = 0.0;
                    }
                    if (velocity < -0.3) {
                      return /* UpdateWithSideEffects */Block.__(2, [
                                state,
                                (function (self) {
                                    return Curry._1(self[/* send */3], /* ToggleMenu */Block.__(0, [false]));
                                  })
                              ]);
                    } else if (action[0] < state[/* nav */1][/* width */3][0] / 2.0) {
                      return /* UpdateWithSideEffects */Block.__(2, [
                                state,
                                (function (self) {
                                    return Curry._1(self[/* send */3], /* ToggleMenu */Block.__(0, [false]));
                                  })
                              ]);
                    } else {
                      return /* Update */Block.__(0, [state]);
                    }
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  make ,
  
}
/*  Not a pure module */
