// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Home$ReactTemplate from "./Home.bs.js";
import * as Page1$ReactTemplate from "./Page1.bs.js";
import * as Page2$ReactTemplate from "./Page2.bs.js";
import * as Page3$ReactTemplate from "./Page3.bs.js";
import * as ReactTransitionGroup$ReactTemplate from "./ReactTransitionGroup.bs.js";

function routeToString(param) {
  switch (param) {
    case 0 : 
        return "/";
    case 1 : 
        return "/page1";
    case 2 : 
        return "/page2";
    case 3 : 
        return "/page3";
    
  }
}

function urlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "page1" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Page1 */1;
          }
      case "page2" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Page2 */2;
          }
      case "page3" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Page3 */3;
          }
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

function routeToTitle(route) {
  switch (route) {
    case 0 : 
        return "Home";
    case 1 : 
        return "Page1";
    case 2 : 
        return "Page2";
    case 3 : 
        return "Page3";
    
  }
}

function routeToComponent(currentRoute) {
  var withCSSTransition = function (component, route) {
    return ReasonReact.element(/* Some */[routeToTitle(route)], /* None */0, ReactTransitionGroup$ReactTemplate.CSSTransition[/* make */0](true, 900, "routeTransition", /* array */[component]));
  };
  switch (currentRoute) {
    case 0 : 
        return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Home$ReactTemplate.make(/* array */[])), /* Home */0);
    case 1 : 
        return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Page1$ReactTemplate.make(/* array */[])), /* Page1 */1);
    case 2 : 
        return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Page2$ReactTemplate.make(/* array */[])), /* Page2 */2);
    case 3 : 
        return withCSSTransition(ReasonReact.element(/* None */0, /* None */0, Page3$ReactTemplate.make(/* array */[])), /* Page3 */3);
    
  }
}

export {
  routeToString ,
  urlToRoute ,
  routeToTitle ,
  routeToComponent ,
  
}
/* ReasonReact Not a pure module */
