// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Home");

var html = "\n  <h1>Home</h1>\n  <p>This is a simple App Shell starter kit that you can use to get started building your <a target=\"_blank\" href=\"https://developers.google.com/web/progressive-web-apps/\">PWA</a> with the power of <a target=\"_blank\" href=\"https://reasonml.github.io\">Reason</a> and <a target=\"_blank\" href=\"https://reasonml.github.io/reason-react/\">ReasonReact</a>.</p>\n  <p>Read the <a target=\"_blank\" href=\"\">tutorial for this App Shell starter kit on Medium</a>.</p>\n  <p>Get the source on <a target=\"_blank\" href=\"\">Github</a>.</p>\n  <p>What's inside?</p>\n  <ul>\n    <li>Initialized via <a target=\"_blank\" href=\"https://github.com/reasonml-community/reason-scripts\">Create React App (with reason-scripts)</a></li>\n    <li>SPA routing with <a target=\"_blank\" href=\"https://reasonml.github.io/reason-react/docs/en/router.html\">ReasonReact's Router</a> and a helper <code>&lt;Link /&gt;</code> component</li>\n    <li>Uses <code>(route, title)</code> tuples for routes</li>\n    <li>A navigation that, when open, responds to touch&mdash;so you're free to use swiping gestures in your app</li>\n    <li>One component per view</li>\n  </ul>\n  <p>In total, <code>app.re</code> is just around ~250 lines. Dive in, and change what you need!</p>\n  <h2>UI Inspiration</h2>\n  <ul>\n    <li><a target=\"_blank\" href=\"https://flowdash.co/\">Flow Dashboard</a></li>\n    <li><a target=\"_blank\" href=\"https://material.angular.io/components/categories\">Angular Material</a></li>\n  </ul>\n";

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: "Home",
                          dangerouslySetInnerHTML: {
                            __html: html
                          }
                        });
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

export {
  component ,
  html ,
  make ,
  
}
/* component Not a pure module */
