// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var html = "\n  <h1>Rescript React Boilerplate</h1>\n  <p>An opinionated implementation of the following technologies:</p>\n  <ul>\n    <li>ReScript & React</li>\n    <li>Simple routing using <a target=\"_blank\" href=\"https://rescript-lang.org/docs/react/latest/router\">ReScript's built in router</a></li>\n    <li>Emotion for CSS-in-JS (or check our the <a target=\"_blank\" href=\"https://github.com/persianturtle/rescript-react-boilerplate/tree/sass\">Sass branch</a>)</li>\n    <li>Quick and dirty route transitions via <a target=\"_blank\" href=\"https://github.com/reactjs/react-transition-group\">ReactTransitionGroup</a></li>\n    <li><a target=\"_blank\" href=\"https://github.com/http-party/http-server\">http-server</a> for a quick and easy development server</li>\n    <li><a target=\"_blank\" href=\"https://esbuild.github.io/\">esbuild</a> for fast bundling</li>\n  </ul>\n  <h2>Getting Started</h2>\n  <pre><code class=\"sh language-sh\">npm install\nnpm start\nopen http://localhost:8081\n  </code></pre>\n  <h2>Demo</h2>\n  <img src=\"/img/demo.gif\" alt=\"Demo\" />\n  <h2>Tutorial</h2>\n  <p>(Video overview coming soon)</p>\n  <h2>Development Environment</h2>\n  <p>Since we're using ReScript and esbuild, our build times are fast.</p>\n  <p>Because of this, we use <a target=\"_blank\" href=\"https://github.com/paulmillr/chokidar\">chokidar (a cross-platform file watcher)</a> to watch for changes and then rebuild the <code>dist</code> directory on every change. The <code>dist</code> directory is the same whether in development or in production.</p>\n  <p>The build should work on macOS, Windows & Linux.</p>\n  <img src=\"/img/start.png\" alt=\"Example npm start output\" />\n";

function Home(Props) {
  return React.createElement("div", {
              className: "Home",
              dangerouslySetInnerHTML: {
                __html: html
              }
            });
}

var make = Home;

export {
  html ,
  make ,
  
}
/* react Not a pure module */
