// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as App$ReactTemplate from "./App.bs.js";
import * as Router$ReactTemplate from "./Router.bs.js";

((require('../../../src/Index.scss')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Router$ReactTemplate.WithRouter[/* make */1]((function (currentRoute) {
                return ReasonReact.element(undefined, undefined, App$ReactTemplate.make(currentRoute, /* array */[]));
              }))), "root");

export {
  
}
/*  Not a pure module */
