// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as App$ReasonCarousel from "./App.bs.js";
import * as Router$ReasonCarousel from "./Router.bs.js";

 import { createGlobalStyle } from "styled-components" 
;

var sc = (
      createGlobalStyle`
        body {
          margin: 0;
          font-family: Helvetica, Arial, sans-serif;
        }

        h1, h2, h3 {
          font-weight: normal;
        }

        img {
          display: block;
          max-width: 100%;
        }

        a {
          cursor: pointer;
        }
      `
    );

var GlobalStyles = /* module */[/* sc */sc];

ReactDOMRe.renderToElementWithId(React.createElement(React.Fragment, undefined, React.createElement(sc, { }), React.createElement(Router$ReasonCarousel.WithRouter[/* make */0], {
              children: (function (currentRoute) {
                  return React.createElement(App$ReasonCarousel.make, {
                              currentRoute: currentRoute
                            });
                })
            })), "root");

export {
  GlobalStyles ,
  
}
/*  Not a pure module */
