// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Page1(Props) {
  return React.createElement("div", {
              className: "Page1"
            }, React.createElement("h1", undefined, "Page1"));
}

var make = Page1;

export {
  make ,
  
}
/* react Not a pure module */
