// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Page3(Props) {
  return React.createElement("div", {
              className: "Page3"
            }, React.createElement("h1", undefined, "Page3"));
}

var make = Page3;

export {
  make ,
  
}
/* react Not a pure module */
