// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Page2(Props) {
  return React.createElement("div", {
              className: "Page2"
            }, React.createElement("h1", undefined, "Page2"));
}

var make = Page2;

export {
  make ,
  
}
/* react Not a pure module */
