// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var TransitionGroup = /* module */[];

var CSSTransition = /* module */[];

export {
  TransitionGroup ,
  CSSTransition ,
  
}
/* No side effect */
