// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as ReactTransitionGroup from "react-transition-group";

require("../../../src/ReactTransitionGroup.scss");

function make(children) {
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.TransitionGroup, { }, children);
}

var TransitionGroup = /* module */[/* make */make];

function make$1(_in, timeout, classNames, children) {
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.CSSTransition, {
              in: _in,
              timeout: timeout,
              classNames: classNames
            }, children);
}

var CSSTransition = /* module */[/* make */make$1];

export {
  TransitionGroup ,
  CSSTransition ,
  
}
/*  Not a pure module */
