// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as ReactTransitionGroup from "react-transition-group";

function make(show, timeout, classNames, children) {
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.CSSTransition, {
              in: show,
              timeout: timeout,
              classNames: classNames
            }, children);
}

var CSSTransition = /* module */[/* make */make];

function make$1(children) {
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.TransitionGroup, {
              component: null
            }, children);
}

var TransitionGroup = /* module */[/* make */make$1];

export {
  CSSTransition ,
  TransitionGroup ,
  
}
/* ReasonReact Not a pure module */
