// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Home$ReactTemplate from "./Home.bs.js";
import * as Page1$ReactTemplate from "./Page1.bs.js";
import * as Page2$ReactTemplate from "./Page2.bs.js";
import * as Page3$ReactTemplate from "./Page3.bs.js";

var routes_000 = /* record */[
  /* href */"/",
  /* title */"Home",
  /* component */ReasonReact.element(undefined, undefined, Home$ReactTemplate.make(/* array */[]))
];

var routes_001 = /* :: */[
  /* record */[
    /* href */"/page1",
    /* title */"Page1",
    /* component */ReasonReact.element(undefined, undefined, Page1$ReactTemplate.make(/* array */[]))
  ],
  /* :: */[
    /* record */[
      /* href */"/page2",
      /* title */"Page2",
      /* component */ReasonReact.element(undefined, undefined, Page2$ReactTemplate.make(/* array */[]))
    ],
    /* :: */[
      /* record */[
        /* href */"/page3",
        /* title */"Page3",
        /* component */ReasonReact.element(undefined, undefined, Page3$ReactTemplate.make(/* array */[]))
      ],
      /* [] */0
    ]
  ]
];

var routes = /* :: */[
  routes_000,
  routes_001
];

function hrefToPath(href) {
  return Belt_List.fromArray(href.replace((/(^\/)|(\/$)/), "").split("/"));
}

function urlToRoute(url) {
  var match = Belt_List.getBy(routes, (function (route) {
          return Caml_obj.caml_equal(url[/* path */0], hrefToPath(route[/* href */0]));
        }));
  if (match !== undefined) {
    return match;
  } else {
    return Belt_List.headExn(routes);
  }
}

var component = ReasonReact.reducerComponent("WithRouter");

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function (self) {
              var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
                      return Curry._1(self[/* send */3], /* ChangeRoute */[urlToRoute(url)]);
                    }));
              return Curry._1(self[/* onUnmount */4], (function (param) {
                            return ReasonReact.Router[/* unwatchUrl */2](watcherID);
                          }));
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return Curry._1(children, self[/* state */1]);
            }),
          /* initialState */(function (param) {
              return urlToRoute(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0));
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [action[0]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var WithRouter = /* module */[
  /* component */component,
  /* make */make
];

var component$1 = ReasonReact.statelessComponent("Link");

function make$1(href, $staropt$star, children) {
  var className = $staropt$star !== undefined ? $staropt$star : "";
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReactDOMRe.createElementVariadic("a", {
                          className: className,
                          href: href,
                          onClick: Curry._1(self[/* handle */0], (function ($$event, _self) {
                                  $$event.preventDefault();
                                  return ReasonReact.Router[/* push */0](href);
                                }))
                        }, children);
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* jsElementWrapped */component$1[/* jsElementWrapped */13]
        ];
}

var Link = /* module */[
  /* component */component$1,
  /* make */make$1
];

var component$2 = ReasonReact.statelessComponent("NavLink");

function make$2(href, children) {
  return /* record */[
          /* debugName */component$2[/* debugName */0],
          /* reactClassInternal */component$2[/* reactClassInternal */1],
          /* handedOffState */component$2[/* handedOffState */2],
          /* willReceiveProps */component$2[/* willReceiveProps */3],
          /* didMount */component$2[/* didMount */4],
          /* didUpdate */component$2[/* didUpdate */5],
          /* willUnmount */component$2[/* willUnmount */6],
          /* willUpdate */component$2[/* willUpdate */7],
          /* shouldUpdate */component$2[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, make((function (currentRoute) {
                                var match = currentRoute[/* href */0] === href;
                                return ReasonReact.element(undefined, undefined, make$1(href, match ? "active" : "", children));
                              })));
            }),
          /* initialState */component$2[/* initialState */10],
          /* retainedProps */component$2[/* retainedProps */11],
          /* reducer */component$2[/* reducer */12],
          /* jsElementWrapped */component$2[/* jsElementWrapped */13]
        ];
}

var NavLink = /* module */[
  /* component */component$2,
  /* make */make$2
];

export {
  routes ,
  hrefToPath ,
  urlToRoute ,
  WithRouter ,
  Link ,
  NavLink ,
  
}
/* routes Not a pure module */
