// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

function first(touchlist) {
  return Caml_array.caml_array_get(touchlist, 0);
}

var TouchList = /* module */[/* first */first];

export {
  TouchList ,
  
}
/* No side effect */
